# パッケージ雛形: workers/wrangler.toml

# Cloudflare プロジェクト設定
name = "undefined"        # 任意のプロジェクト名
main = "workers.js"
compatibility_date = "2025-06-15"  # 発行日付
type = "javascript"

# 以下は配布先ユーザーが自身のアカウント情報に置き換え
account_id = "undefined"   # Cloudflare Account ID
workers_dev = false                  # true で *.workers.dev のみ使用

[env.production]
# 本番用 Route と Zone の設定
route = "undefined/*"        # 例: api.example.com/*
zone_id = "undefined"         # 上記サブドメインに対応する Zone ID